cat:
	cat Justfile

tests:
	fpc JabbaUtilsTests.pas -otests
	./tests
	fpc RangeUnitTests.pas -otests
	./tests
	fpc ArrayUtilsTests.pas -otests
	./tests
	#
	rm tests
	just clean

clean:
	\rm -f ./*.o ./*.ppu ./GPATH ./GRTAGS ./GTAGS
	\rm -f ./main ./*Tests ./*Demo
